//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ConcreteProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConcreteProduct()
        {
            this.ConcreteProductDetails = new HashSet<ConcreteProductDetails>();
        }
        [Key]
        public int ConcreteProduct_Id { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "* Required")]
        [MinLength(2, ErrorMessage = "Incorrect Input:Your input must be long from two characters")]
        public string ConcreteProductName { get;set;}
        public string ImagePath { get; set; }
        public string About { get; set; }
        [Key]
        public int ProductType_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConcreteProductDetails> ConcreteProductDetails { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
